import { Inter } from 'next/font/google'
import './globals.css'
import NavBarComp from './components/Navigation/NavBarComp'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='mytheme'>
      <body className={inter.className}>
        <NavBarComp />
        {children}
        <Footer />
      </body>
    </html>
  )
}
